experiment:
  name: "model_two"
  seed: &seed 42
  device: "auto"

data:
  target: "Survived"
  original:
    train_path: "data/processed/raw/train_dataset.parquet"
    test_path: "data/processed/raw/test_dataset.parquet"
  binned:
    train_path: "data/processed/raw/train_dataset.parquet"
    test_path: "data/processed/raw/test_dataset.parquet"

validation:
  type: "stratified_kfold"
  n_splits: 5
  shuffle: true
  random_state: *seed

preprocessing:
  scaler: "standard"

metrics:
  primary: "f1"
  log:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"

model:
  name: "model_two"
  params: 
    hidden_features: 32
    out_features: 1

criterion:
  name: "bce_with_logits"

optimizer:
  name: "adam"
  params:
    lr: 0.001

training:
  epochs: 50
  batch_size: 32
