experiment:
  name: ensembles
  seed: &seed 42

data:
  target: Survived
  original:
    train_path: data/processed/original/train_dataset.parquet
    test_path: data/processed/original/test_dataset.parquet
  binned:
    train_path: data/processed/binned/train_dataset.parquet
    test_path: data/processed/binned/test_dataset.parquet

validation:
  n_splits: 5
  shuffle: true
  random_state: *seed

metrics:
  primary: f1
  log: [accuracy, precision, recall, f1, roc_auc]

base_configs:
  - configs/classic_config/logreg_l2.yaml
  - configs/classic_config/random_forest_classifier.yaml
  - configs/classic_config/catboost_classifier.yaml

methods: [average, voting_hard, voting_soft, stacking_linear, stacking_ridge]

voting:
  weights: [1, 2, 2]

stacking:
  n_splits: 5
  linear:
    fit_intercept: true
  ridge:
    alpha: 1.0
    fit_intercept: true
